/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DataRoutesImport } from './routes/dataRoutes'
import { Route as DataDisplayImport } from './routes/dataDisplay'
import { Route as AboutImport } from './routes/about'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DataRoutesRoute = DataRoutesImport.update({
  path: '/dataRoutes',
  getParentRoute: () => rootRoute,
} as any)

const DataDisplayRoute = DataDisplayImport.update({
  path: '/dataDisplay',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/dataDisplay': {
      id: '/dataDisplay'
      path: '/dataDisplay'
      fullPath: '/dataDisplay'
      preLoaderRoute: typeof DataDisplayImport
      parentRoute: typeof rootRoute
    }
    '/dataRoutes': {
      id: '/dataRoutes'
      path: '/dataRoutes'
      fullPath: '/dataRoutes'
      preLoaderRoute: typeof DataRoutesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutRoute,
  DataDisplayRoute,
  DataRoutesRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/dataDisplay",
        "/dataRoutes"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dataDisplay": {
      "filePath": "dataDisplay.tsx"
    },
    "/dataRoutes": {
      "filePath": "dataRoutes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
